    <footer id="section-footer" class="footer moto-section" data-widget="section" data-container="section" data-moto-sticky="{mode:'smallHeight', direction:'bottom'}">
                    <div class="moto-widget moto-widget-row row-fixed" data-widget="row"><div class="container-fluid"><div class="row"><div class="moto-cell col-sm-12" data-container="container"><div data-spacing="lasa" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_system_7" style="text-align: center;">GET OUR SPECIAL OFFERS<br></p></div></div><div data-spacing="aama" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-medium moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_system_9" style="text-align: center;"><strong>and the Latest CrossFit Tips and Tricks!</strong></p></div></div></div></div></div></div><div class="moto-widget moto-widget-row row-fixed" data-widget="row"><div class="container-fluid"><div class="row"><div class="moto-cell col-sm-4 undefined" data-container="container"></div><div class="moto-cell col-sm-4" data-container="container"><div data-widget-id="wid__mail_chimp__59a5189c1fbbe" class="moto-widget moto-widget-mail_chimp moto-widget-contact_form moto-preset-3 moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-medium moto-spacing-left-auto " data-widget="mail_chimp" data-preset="3">
    <div ng-controller="widget.MailChimp.Controller" ng-init="listId = ''">

        
        <form class="moto-widget-contact_form-form" role="form" name="subscribeForm" ng-submit="submit()" novalidate>
            <div ng-show="sending" class="contact-form-loading"></div>
                                                <div class="moto-widget-contact_form-group">
                        <label for="field_email" class="moto-widget-contact_form-label">Enter your e-mail address</label>
                        <input type="text" class="moto-widget-contact_form-field moto-widget-contact_form-input" placeholder="Enter your e-mail address *"  ng-blur="validate('email')" required  ng-model-options="{ updateOn: 'blur' }" name="email" id="sub_field_email" ng-model="message.email"/>
                                                    <span class="moto-widget-contact_form-field-error ng-cloak" ng-cloak ng-show="subscribeForm.email.$invalid && !subscribeForm.email.$pristine && !subscribeForm.email.emailInvalid" >Field is required</span>
                            <span class="moto-widget-contact_form-field-error ng-cloak" ng-cloak ng-show="subscribeForm.email.emailInvalid && !subscribeForm.email.$pristine" >Incorrect email</span>
                                            </div>
                                                                                    
                            <div class="moto-widget-contact_form-success ng-cloak" ng-cloak ng-show="emailSent">
                    You have successfully subscribed to the newsletter
                </div>
                <div class="moto-widget-contact_form-danger ng-cloak" ng-cloak ng-show="emailError && !isSubscribed">
                    You were not subscribed. Please try again
                </div>
                <div class="moto-widget-contact_form-danger ng-cloak" ng-cloak ng-show="emailError && isSubscribed">
                    You are already subscribed to this newsletter
                </div>
            
            <div class="moto-widget-contact_form-buttons">
                <div class="moto-widget moto-widget-button moto-preset-3 moto-align-left" data-preset="3" data-align="left">
                    <a ng-click="submit()" class="moto-widget-button-link moto-size-medium"
                       data-size="medium"><span class="fa moto-widget-theme-icon"></span><span class="moto-widget-button-label">SUBSCRIBE</span></a>
                </div>
                <button type="submit" class="hidden"></button>
            </div>
        </form>
    </div>
</div></div><div class="moto-cell col-sm-4" data-container="container"></div></div></div></div><div class="moto-widget moto-widget-row row-fixed" data-widget="row"><div class="container-fluid"><div class="row"><div class="moto-cell col-sm-12" data-container="container"><div data-spacing="mama" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-medium moto-spacing-right-auto moto-spacing-bottom-medium moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_system_7" style="text-align: center;">LET'S STAY CONNECTED<br></p></div></div><div data-widget-id="wid__social_links__59a5189c1fe02" class="moto-widget moto-widget-social-links moto-preset-3 moto-align-center moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-large moto-spacing-left-auto " data-widget="social_links" data-preset="3">
        <ul class="moto-widget-social-links-list">
                                                        <li class="moto-widget-social-links-item">
                        <a href="http://demolink.motocms.com/" class="moto-widget-social-links-link moto-widget-social-links-link_facebook" data-provider="facebook" target="_blank"></a>
                    </li>
                                                                                <li class="moto-widget-social-links-item">
                        <a href="http://demolink.motocms.com/" class="moto-widget-social-links-link moto-widget-social-links-link_googleplus" data-provider="googleplus" target="_blank"></a>
                    </li>
                                                                                <li class="moto-widget-social-links-item">
                        <a href="http://demolink.motocms.com/" class="moto-widget-social-links-link moto-widget-social-links-link_twitter" data-provider="twitter" target="_blank"></a>
                    </li>
                                                                                <li class="moto-widget-social-links-item">
                        <a href="http://demolink.motocms.com/" class="moto-widget-social-links-link moto-widget-social-links-link_pinterest" data-provider="pinterest" target="_blank"></a>
                    </li>
                                                                                <li class="moto-widget-social-links-item">
                        <a href="http://demolink.motocms.com/" class="moto-widget-social-links-link moto-widget-social-links-link_linkedin" data-provider="linkedin" target="_blank"></a>
                    </li>
                                                                                    </ul>
    </div></div></div></div></div><div data-css-name="moto-container_footer_57b6fe0823" class="moto-widget moto-widget-container moto-container_footer_57b6fe0823" data-widget="container" data-container="container"><div class="moto-widget moto-widget-row row-fixed" data-widget="row"><div class="container-fluid"><div class="row"><div class="moto-cell col-sm-3 undefined" data-container="container"><div data-spacing="lasa" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_system_1"><a class="moto-link" data-id="1" data-action="page" href="index.html">IRONMASS</a><br></p></div></div><div data-widget-id="wid__spacer__59a5189c201bf" class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto "
    data-widget="spacer" data-preset="default" data-spacing="aaaa" data-visible-on="mobile-v">
    <div class="moto-widget-spacer-block" style="height:10px"></div>
</div><div class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_system_9">Regardless of what is your current shape now, after visiting our CrossFit sessions you will be at the top of your physical conditions!<br></p></div></div></div><div class="moto-cell col-sm-3" data-container="container"><div data-spacing="lasa" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_192">NAVIGATIONS<br></p></div></div><div data-widget-id="wid__spacer__59a5189c202f1" class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto "
    data-widget="spacer" data-preset="default" data-spacing="aaaa" data-visible-on="mobile-v">
    <div class="moto-widget-spacer-block" style="height:10px"></div>
</div><div class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_193"><a class="moto-link" data-id="9" data-action="page" href="about/index.html">About Us</a><br><a class="moto-link" data-id="10" data-action="page" href="programs/index.html">Programs</a><br><a class="moto-link" data-id="11" data-action="page" href="coaches/index.html">Coaches</a><br><a class="moto-link" data-id="3" data-action="blog.index" href="blog/index.html">Blog</a><br></p></div></div></div><div class="moto-cell col-sm-3" data-container="container"><div data-spacing="lasa" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_192">CONTACT INFORMATION<br></p></div></div><div data-widget-id="wid__spacer__59a5189c210e3" class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto "
    data-widget="spacer" data-preset="default" data-spacing="aaaa" data-visible-on="mobile-v">
    <div class="moto-widget-spacer-block" style="height:11px"></div>
</div><div class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_219">4096 N Highland St, Arlington, VA</p><p class="moto-text_219">32101, USA</p><p class="moto-text_219"><a class="moto-link" data-action="mail" href="mailto:ironmass@demolink.org">ironmass@demolink.org</a><br></p></div></div></div><div class="moto-cell col-sm-3" data-container="container"><div data-spacing="lasa" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_192">WE ARE OPEN<br></p></div></div><div data-widget-id="wid__spacer__59a5189c21212" class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto "
    data-widget="spacer" data-preset="default" data-spacing="aaaa" data-visible-on="mobile-v">
    <div class="moto-widget-spacer-block" style="height:11px"></div>
</div><div data-draggable-disabled="" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-widget="text" data-preset="default"><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_219">Mon-Thu:&nbsp;&nbsp;&nbsp; 9:30 - 21:00<br>Fri:&nbsp;&nbsp; 6:00 - 21:00<br>Sat:&nbsp;&nbsp; 10:00 - 15:00</p></div></div></div></div></div></div><div data-widget-id="wid__spacer__59a5189c21378" class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto "
    data-widget="spacer" data-preset="default" data-spacing="laaa" data-visible-on="mobile-v">
    <div class="moto-widget-spacer-block" style="height:0px"></div>
</div></div><div data-css-name="moto-container_footer_57b6ffda24" class="moto-widget moto-widget-container moto-container_footer_57b6ffda24" data-widget="container" data-container="container" data-draggable-disabled=""><div class="moto-widget moto-widget-row row-fixed" data-widget="row" data-draggable-disabled=""><div class="container-fluid"><div class="row"><div class="moto-cell col-sm-12" data-container="container"><div data-spacing="sasa" class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-small moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default" data-draggable-disabled=""><div class="moto-widget-text-content moto-widget-text-editable"><p class="moto-text_system_14">© 2017 All rights reserved by EQUINEINTEL&nbsp; |&nbsp; <span class="moto-color1_3"><a class="moto-link" data-id="18" data-action="page" href="terms/index.html">Terms</a> / <a class="moto-link" data-id="17" data-action="page" href="privacy-policy/index.html">Privacy </a></span><span class="moto-color_custom2">| Designed by </span><a href="https://motocms.com/" target="_blank" rel="nofollow" data-action="url">ZhenZhang</a><br></p></div></div></div></div></div></div></div>            </footer>